# Generated by Django 5.2.4 on 2025-08-29 11:01

import apps.common.utils
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Категория по бизнес-плану',
                'verbose_name_plural': 'Категории по бизнес-плану',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CounterpartyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('post', models.CharField(blank=True, default='', max_length=64)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Counterparties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inn', models.CharField(db_index=True, max_length=12)),
                ('name_from_excel', models.CharField(max_length=512)),
                ('name_from_dadata', models.CharField(blank=True, default='', max_length=512)),
                ('address_from_excel', models.CharField(max_length=1024)),
                ('address_from_dadata', models.CharField(blank=True, default='', max_length=1024)),
                ('counterparties_type', models.CharField(blank=True, choices=[('LEGAL', 'ЮЛ'), ('INDIVIDUAL', 'ИП')], default='', max_length=10)),
                ('branch_type', models.CharField(blank=True, choices=[('MAIN', 'Головная организация'), ('BRANCH', 'Филиал')], default='', max_length=20)),
                ('kpp', models.CharField(blank=True, max_length=9, null=True)),
                ('ogrn', models.CharField(max_length=13)),
                ('ogrn_date', models.DateTimeField()),
                ('name_full_with_opf', models.CharField(max_length=512)),
                ('okved', models.CharField(max_length=8)),
                ('opf_full', models.CharField(max_length=64)),
                ('opf_short', models.CharField(max_length=8)),
                ('registration_date', models.DateTimeField()),
                ('liquidation_date', models.DateTimeField(blank=True, null=True)),
                ('business_plan_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_plan_categories', to='companies.businessplancategory')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='companies.category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='companies.counterparties')),
                ('counterparty_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='companies.counterpartycontact')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(max_length=32)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=16, null=True)),
                ('counterparties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='companies.counterparties')),
            ],
        ),
        migrations.CreateModel(
            name='CounterpartiesState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuality_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Действующая'), ('LIQUIDATING', 'Ликвидируется'), ('LIQUIDATED', 'Ликвидирована'), ('BANKRUPT', 'Банкротство'), ('REORGANIZING', 'В процессе присоединения к другому ЮЛ')], default='ACTIVE', max_length=37)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('counterparties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='companies.counterparties')),
            ],
        ),
        migrations.CreateModel(
            name='DebtCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_total', models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.00'), max_digits=21, null=True)),
                ('debt_acts', models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.00'), max_digits=21, null=True)),
                ('debt_current', models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.00'), max_digits=21, null=True)),
                ('debt_overdue', models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.00'), max_digits=21, null=True)),
                ('debt_origin_date', models.DateField(blank=True, null=True)),
                ('credit_total', models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.00'), max_digits=21, null=True)),
                ('date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_and_credits', to='companies.contract')),
            ],
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(blank=True, default=apps.common.utils.upload_log_file_name_of_nine, max_length=255, null=True)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(upload_to='uploads/%Y/%m')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='companies_c_contrac_a924ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('contract_number', 'counterparties')},
        ),
        migrations.AddIndex(
            model_name='counterpartiesstate',
            index=models.Index(fields=['status', 'actuality_date'], name='companies_c_status_1b9c87_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparties',
            index=models.Index(fields=['inn', 'counterparties_type', 'branch_type', 'liquidation_date'], name='companies_c_inn_7967df_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadlog',
            index=models.Index(fields=['uploaded_by'], name='companies_u_uploade_4a82e4_idx'),
        ),
    ]
