# Generated by Django 5.2.4 on 2025-07-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentrole',
            name='department',
        ),
        migrations.AlterField(
            model_name='departmentrole',
            name='ldap_group_dn',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='departmentrole',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
